# Configuration for 1D periodic acoustic wave problem
# Designed for comprehensive testing of the 1D spectral solver
problem: acoustic1d

grid:
  N: 256            # number of points (power of 2 recommended for spectral methods)
  Lx: 2.0           # domain length [0, Lx) with periodic BCs
  dealias: true     # apply 2/3-rule dealiasing

physics:
  gamma: 1.4        # adiabatic index

integration:
  t0: 0.0
  t_end: 1.0        # short time for testing
  cfl: 0.4          # Upper bound for dt
  scheme: rk4        # Fallback for non-adaptive
  output_interval: 0.01
  checkpoint_interval: 0.5
  spectral_filter:
    enabled: true
    p: 8            # even integer >= 2
    alpha: 36.0     # filter strength

# Initial conditions smoothing (optional)
initial_conditions_smoothing:
  enabled: false        # Disabled by default for acoustic1d
  kernel_size: 0.01     # 1% of domain length
  mode: "wrap"          # Periodic boundary conditions
  variables: ["density", "velocity", "pressure"]
  diagnostic_output: false

# Adaptive time-stepping configuration
adaptive:
  enabled: true
  scheme: rk45          # rk23, rk45, rk78
  rtol: 1e-6            # Relative tolerance
  atol: 1e-8            # Absolute tolerance
  safety_factor: 0.9
  min_dt_factor: 0.1
  max_dt_factor: 5.0
  max_rejections: 10
  fallback_scheme: rk4

initial_conditions:
  rho0: 1.0         # background density
  u0: 0.0           # background velocity (zero for pure acoustic test)
  p0: 1.0           # background pressure
  amplitude: 1.0e-3 # small amplitude for linear regime testing
  k: 1              # fundamental mode (one wavelength in domain)

io:
  outdir: outputs/acoustic1d
  save_spectra: true

video:
  fps: 30
  width: 1920
  height: 1080
  scale: 2.0
  frame_dpi: 150
  codec: libopenh264
  crf: 18
  preset: medium
  pix_fmt: yuv420p

monitoring:
  enabled: true
  step_interval: 100
  include_conservation: true
  include_timestep: true
  include_time: true