# Configuration for 1D acoustic wave problem with Neumann/open BCs
problem: acoustic1d

grid:
  N: 256
  Lx: 1.0
  x0: 0.5               # wave center
  basis: legendre         # Legendre basis for non-periodic BCs
  bc: neumann           # zero-gradient boundaries
  precision: double

physics:
  gamma: 1.4

integration:
  t0: 0.0
  t_end: 0.5
  cfl: 0.3
  scheme: rk45
  rtol: 1e-6
  atol: 1e-8
  output_interval: 0.05
  checkpoint_interval: 0.1
  spectral_filter:
    enabled: true
    p: 8
    alpha: 50.0

# Initial conditions for acoustic wave
initial_conditions:
  amplitude: 0.01        # small amplitude for linear regime
  width: 0.1            # Gaussian width
  center: 0.5           # wave center

# Adaptive time-stepping
adaptive:
  enabled: true
  scheme: rk45
  rtol: 1e-6
  atol: 1e-8
  safety_factor: 0.9
  min_dt_factor: 0.1
  max_dt_factor: 5.0
  max_rejections: 10
  fallback_scheme: rk4

# Artificial viscosity for stability
artificial_viscosity:
  enabled: false
  nu_max: 1e-4
  s_ref: 1.0
  s_min: 0.1
  p: 2.0
  epsilon: 1e-12
  variable_weights:
    density: 1.0
    momentum_x: 1.0
    energy: 1.0
  sensor_variable: "density"
  diagnostic_output: false

io:
  outdir: outputs/acoustic_neumann
  save_spectra: true

monitoring:
  enabled: true
  step_interval: 20
  include_conservation: true
  include_timestep: true
  include_time: true
  include_velocity_stats: true
  include_density_stats: true
