# Configuration for 1D acoustic wave with Legendre basis and parallel threading
# Tests OpenMP-enabled Numba kernels for Legendre methods
problem: gaussian_wave1d

grid:
  N: 256            # number of Legendre points
  Lx: 4.0           # domain length [0, Lx]
  basis: legendre   # Use Legendre-Gauss-Lobatto basis
  bc: dirichlet     # Dirichlet boundary conditions
  dealias: false    # Not applicable for Legendre basis
  precision: double

physics:
  gamma: 1.4        # adiabatic index

# Enable parallel threading for OpenMP-enabled Numba kernels
runtime:
  num_threads: 4    # Use 4 threads for parallel Legendre operations

integration:
  t0: 0.0
  t_end: 1.0        # Run for 1 time unit (shorter for testing)
  cfl: 0.3          # Conservative CFL for Legendre
  scheme: rk4       # Stable scheme for Legendre
  output_interval: 0.05     # Frequent outputs for video (20 frames)
  checkpoint_interval: 0.2  # Checkpoints every 0.2 time units
  spectral_filter:
    enabled: true
    p: 8            # even integer >= 2
    alpha: 36.0     # filter strength

# Initial conditions - Gaussian pulse
initial_conditions:
  wave_type: traveling  # traveling wave packet
  rho0: 1.0         # background density
  u0: 0.0           # background velocity (at rest)
  p0: 1.0           # background pressure
  amplitude: 1e-3   # Gaussian amplitude (linear regime)
  sigma: 0.2        # Gaussian width
  x0: 2.0           # center at middle of domain

# Output configuration
output:
  outdir: outputs/acoustic_legendre_parallel
  save_fields: true
  save_diagnostics: true
  save_checkpoints: true
