problem: sod
grid:
  N: 256
  Lx: 1.0
  basis: legendre
  bc: dirichlet
  dealias: false
  precision: single
equations:
  gamma: 1.4
integration:
  t0: 0.0
  t_end: 0.2
  cfl: 0.15
  scheme: rk4
  output_interval: 0.01
  spectral_filter:
    enabled: true
    p: 16
    alpha: 150.0
    interval: 1
  adaptive:
    enabled: true
    scheme: rk45
    rtol: 1e-6
    atol: 1e-8
    safety_factor: 0.9
    min_dt_factor: 0.1
    max_dt_factor: 5.0
    max_rejections: 10
    fallback_scheme: rk4
initial_conditions:
  left:
    rho: 1.0
    u: 0.0
    p: 1.0
  right:
    rho: 0.125
    u: 0.0
    p: 0.1
initial_conditions_smoothing:
  enabled: false
  kernel_size: 0.1
  mode: constant
  variables: [density, velocity, pressure]
  diagnostic_output: false
monitoring:
  enabled: true
  step_interval: 5
  include_conservation: true
  include_timestep: true
  include_time: true
  include_velocity_stats: true
  include_density_stats: true
runtime:
  num_threads: auto

artificial_viscosity:
  enabled: true
  nu_max: 0.05
  s_ref: 1.0
  s_min: 0.1
  p: 2.0
  epsilon: 1e-12
  variable_weights:
    density: 1.0
    momentum_x: 1.0
    momentum_y: 1.0
    momentum_z: 1.0
    energy: 1.0
  sensor_variable: density
  diagnostic_output: false
