# Legendre-based 1D Sod shock tube (non-periodic BC)
problem: sod

grid:
  N: 32             # Low resolution for quick test
  Lx: 1.0
  basis: legendre
  bc: dirichlet     # reflective/dirichlet at endpoints for momentum
  dealias: false    # not applicable to Legendre, left false

physics:
  gamma: 1.4

integration:
  t0: 0.0
  t_end: 0.02      # very short run for quick test
  cfl: 0.1         # conservative CFL for low resolution
  scheme: rk4
  output_interval: 0.002  # frequent output for verification
  checkpoint_interval: 0.005
  spectral_filter:
    enabled: true
    p: 8
    alpha: 36.0

initial_conditions:
  left:
    rho: 1.0
    u: 0.0
    p: 1.0
  right:
    rho: 0.125
    u: 0.0
    p: 0.1

io:
  outdir: outputs/sod_legendre
  save_spectra: true

monitoring:
  enabled: true
  step_interval: 10  # More frequent monitoring for low-res test
  include_conservation: true
  include_timestep: true
  include_time: true

video:
  fps: 30
  width: 1280
  height: 720
  scale: 1.5
  frame_dpi: 120
  codec: h264_videotoolbox
  crf: 20
  preset: medium
  pix_fmt: yuv420p

