# 2D Gaussian Wave Packet Configuration - Y-direction only (Fourier basis)
# Tests 2D Fourier basis with a 1D wave copied along x-direction

problem:
  name: "gaussian_wave2d_y"
  description: "2D Gaussian wave packet traveling in y-direction only (1D copied along x) - Fourier basis"

# Grid configuration
grid:
  Nx: 32                    # Fewer modes in x since it's constant
  Ny: 64                    # More modes in y for the wave
  Lx: 1.0                   # Domain length in x
  Ly: 1.0                   # Domain length in y
  basis_x: "fourier"        # Use Fourier basis in x
  basis_y: "fourier"        # Use Fourier basis in y
  bc: "periodic"            # Periodic boundary conditions
  dealias: true             # Enable dealiasing for Fourier
  precision: "double"       # Use double precision

# Initial conditions
initial_conditions:
  rho0: 1.0                 # Background density
  u0: 0.0                   # Background x-velocity (should stay 0)
  v0: 0.0                   # Background y-velocity
  p0: 1.0                   # Background pressure
  amplitude: 0.1            # Wave amplitude (match 1D)
  sigma: 0.05               # Wave packet width (match 1D)
  y0: 0.5                   # Initial y position (center of domain)
  direction: "up"           # Wave direction: "up" or "down"

# Physics
physics:
  gamma: 1.4                # Adiabatic index
  gravity:
    enabled: false          # No gravity for this test

# Integration
integration:
  t0: 0.0                   # Start time
  t_end: 1.0                # End time (shorter for y-direction test)
  dt: 1e-4                  # Initial time step
  scheme: "rk4"             # 4th order Runge-Kutta
  cfl: 0.5                  # CFL number
  adaptive_dt: true         # Use adaptive time stepping
  spectral_filter:
    enabled: true           # Enable spectral filtering
    p: 8                    # Filter order
    alpha: 36.0             # Filter strength

# Artificial viscosity (small amount for stability)
artificial_viscosity:
  enabled: true
  nu_max: 1e-4              # Maximum viscosity
  s_ref: 1.0                # Reference strain rate
  s_min: 0.1                # Minimum strain rate
  p: 2.0                    # Viscosity power law
  epsilon: 1e-12            # Small number to avoid division by zero
  variable_weights:
    density: 1.0
    momentum_x: 1.0
    momentum_y: 1.0
    energy: 1.0
  sensor_variable: "density"
  diagnostic_output: false

# Output
io:
  outdir: "outputs/gaussian_wave2d_y_fourier"
  output_interval: 0.05     # Output every 0.05 time units
  save_frames: true         # Save frames for video generation
  frames_dir: "frames"      # Subdirectory for frames

# Monitoring
monitoring:
  step_interval: 10         # Print status every 10 steps
  verbose: true             # Verbose output

# Visualization
visualization:
  create_plots: true        # Create analysis plots
  plot_interval: 0.05       # Plot every 0.05 time units
  save_plots: true          # Save plots to disk
