# Configuration for 2D Kelvin-Helmholtz instability problem
problem: khi2d

grid:
  Nx: 512
  Ny: 512
  Lx: 1.0
  Ly: 1.0
  dealias: true
  fft_workers: 4

physics:
  gamma: 1.4

integration:
  t0: 0.0
  t_end: 5.0
  cfl: 0.25
  scheme: rk78
  rtol: 1e-6
  atol: 1e-8
  output_interval: 0.02
  checkpoint_interval: 0.5
  spectral_filter:
    enabled: true
    p: 8
    alpha: 36.0

# Initial conditions smoothing (optional)
initial_conditions_smoothing:
  enabled: false        # Disabled by default for KHI2D problem
  kernel_size: 0.01     # 1% of domain length
  mode: "constant"      # Non-periodic boundary conditions
  variables: ["density", "velocity", "pressure"]
  diagnostic_output: false

# Adaptive time-stepping configuration
adaptive:
  enabled: true
  scheme: rk78          # rk23, rk45, rk78
  rtol: 1e-6            # Tighter relative tolerance
  atol: 1e-8            # Tighter absolute tolerance
  safety_factor: 0.5
  min_dt_factor: 0.1
  max_dt_factor: 2.0
  max_rejections: 10
  fallback_scheme: rk4

# Artificial viscosity configuration
artificial_viscosity:
  enabled: false
  nu_max: 5e-4          # Lower viscosity for 2D
  s_ref: 0.5            # Lower reference smoothness
  s_min: 0.05           # Lower minimum threshold
  p: 1.5                # Gentler scaling
  epsilon: 1e-12        # Small number to avoid division by zero
  variable_weights:
    density: 1.0
    momentum_x: 0.8
    momentum_y: 0.8
    energy: 1.0
  sensor_variable: "density"
  diagnostic_output: true

# Initial conditions
initial_conditions:
  rho_outer: 1.0
  rho_inner: 2.0
  u0: 1.0
  shear_thickness: 0.02
  pressure_outer: 1.0
  pressure_inner: 1.0
  perturb_eps: 0.01
  perturb_sigma: 0.02
  perturb_kx: 2          # wavenumber for sinusoidal modulation in x

io:
  outdir: outputs/khi2d
  save_spectra: true

monitoring:
  enabled: true
  step_interval: 50
  include_conservation: true
  include_timestep: true
  include_time: true
  include_velocity_stats: true
  include_density_stats: true

video:
  # Video generation parameters
  fps: 30                    # Frames per second
  width: 1920                # Output video width (0 = auto from frames)
  height: 1080               # Output video height (0 = auto from frames)
  scale: 2.0                 # Scale factor for frames (1.0 = original size)
  frame_dpi: 150             # DPI for frame generation (higher = better quality)
  quality: high              # Quality preset: low, medium, high

  # FFmpeg encoding parameters
  codec: h264_videotoolbox   # Video codec (h264_videotoolbox, libx264, libopenh264, etc.)
  crf: 23                    # Constant Rate Factor (0-51, lower = better quality)
  preset: medium             # Encoding preset (ultrafast, fast, medium, slow, veryslow)
  pix_fmt: yuv420p           # Pixel format (yuv420p, yuv444p, etc.)
  
  # Additional FFmpeg options
  bitrate: null              # Target bitrate (e.g., "2M" for 2 Mbps, null = use CRF)
  maxrate: null              # Maximum bitrate (e.g., "4M")
  bufsize: null              # Buffer size (e.g., "8M")
  
  # Quality settings
  tune: null                 # Tune for specific content (film, animation, grain, etc.)
  profile: high              # H.264 profile (baseline, main, high, high10, etc.)
  level: 4.1                 # H.264 level (3.0, 3.1, 4.0, 4.1, etc.)