problem: khi2d

grid:
  Nx: 128
  Ny: 128
  Lx: 1.0
  Ly: 1.0
  dealias: true
  fft_workers: 4

physics:
  gamma: 1.4

integration:
  t0: 0.0
  t_end: 5.0
  cfl: 0.25         # Upper bound for dt
  scheme: rk4       # Fallback for non-adaptive
  output_interval: 0.02
  spectral_filter:
    enabled: true
    p: 8
    alpha: 36.0
  
  # Adaptive time-stepping configuration
  adaptive:
    enabled: true
    scheme: rk45    # rk23, rk45, rk78
    rtol: 1e-5      # Slightly relaxed for 2D complexity
    atol: 1e-7      # Absolute tolerance
    safety_factor: 0.9
    min_dt_factor: 0.1
    max_dt_factor: 5.0
    max_rejections: 10
    fallback_scheme: rk4

initial_conditions:
  rho_outer: 1.0
  rho_inner: 2.0
  u0: 1.0
  shear_thickness: 0.02
  pressure_outer: 1.0
  pressure_inner: 1.0
  perturb_eps: 0.01
  perturb_sigma: 0.02
  perturb_kx: 2  # wavenumber for sinusoidal modulation in x

io:
  outdir: outputs/khi2d_adaptive

video:
  fps: 30
  codec: h264_videotoolbox
  crf: 18
  pix_fmt: yuv420p

monitoring:
  enabled: true
  step_interval: 50
  include_conservation: true
  include_timestep: true
  include_time: true
  include_velocity_stats: true
  include_density_stats: true
