# Configuration for 2D Rayleigh-Taylor Instability problem
# Mixed BCs: Dirichlet bottom, Neumann top/left/right
# GPU acceleration with PyTorch backend
problem: rti

grid:
  Nx: 256                   # Higher resolution for better visualization
  Ny: 512                   # Height resolution (2x width)
  Lx: 1.0                   # Width of box
  Ly: 2.0                   # Height of box (2x width)
  basis_x: legendre         # Use Legendre in x (non-periodic/outflow)
  basis_y: legendre         # Use Legendre in y (wall/outflow)
  dealias: true
  precision: single
  fft_workers: 4

physics:
  gamma: 1.4

integration:
  t0: 0.0
  t_end: 2.0                # Longer run for full RTI development
  cfl: 0.3                  # Similar to SOD for stability
  scheme: rk4               # Stable scheme like SOD
  output_interval: 0.02     # Very frequent outputs for smooth video (100 frames)
  checkpoint_interval: 0.2
  spectral_filter:
    enabled: true
    p: 8                     # Similar to SOD
    alpha: 36.0             # Similar to SOD

# Initial conditions smoothing (optional Gaussian smoothing)
initial_conditions_smoothing:
  enabled: false

# Adaptive time-stepping configuration (similar to SOD)
adaptive:
  enabled: true
  scheme: rk45              # Similar to SOD
  rtol: 1e-5
  atol: 1e-7
  safety_factor: 0.9        # Similar to SOD
  min_dt_factor: 0.1
  max_dt_factor: 5.0        # Similar to SOD
  max_rejections: 10
  fallback_scheme: rk4

# Artificial viscosity for stability (similar to SOD)
artificial_viscosity:
  enabled: true
  nu_max: 1e-3             # Similar to SOD
  s_ref: 1.0               # Similar to SOD
  s_min: 0.1               # Similar to SOD
  p: 2.0                   # Similar to SOD
  epsilon: 1e-12
  variable_weights:
    density: 1.0
    momentum_x: 1.0
    momentum_y: 1.0
    energy: 1.0
  sensor_variable: "density"
  diagnostic_output: true

# Gravity configuration - downward gravity
gravity:
  enabled: true
  type: "linear"
  gx: 0.0
  gy: -1.0                   # Downward gravity
  gz: 0.0

# Initial conditions for RTI (similar to KHI2D structure)
initial_conditions:
  rho_bottom: 1.0            # Light fluid at bottom
  rho_top: 2.0               # Heavy fluid at top (RT-unstable)
  pressure_bottom: 2.0       # Base pressure at bottom
  shear_thickness: 0.02      # Similar to KHI2D
  perturb_eps: 0.01          # Similar to KHI2D
  perturb_sigma: 0.02        # Similar to KHI2D
  perturb_kx: 2              # Similar to KHI2D
  perturb_ky: 1              # Vertical wavenumber

# Boundary conditions (mixed as requested)
# boundary_conditions:
#   # Bottom boundary (Dirichlet - solid wall)
#   bottom:
#     density: 1.0             # Light fluid at bottom
#     momentum_x: 0.0          # No slip
#     momentum_y: 0.0          # No slip
#     pressure: 2.0            # Base pressure
#   # Top boundary (Neumann - outflow)
#   top: neumann
#   # Left boundary (Neumann - outflow)
#   left: neumann
#   # Right boundary (Neumann - outflow)
#   right: neumann

# Runtime configuration for GPU acceleration
runtime:
  num_threads: 4            # Use parallel Legendre operations

io:
  outdir: outputs/rti
  save_spectra: true

monitoring:
  enabled: true
  step_interval: 50
  include_conservation: true
  include_timestep: true
  include_time: true
  include_velocity_stats: true
  include_density_stats: true

video:
  # Video generation parameters
  fps: 30                    # Frames per second
  width: 1920                # Output video width
  height: 1080               # Output video height
  scale: 2.0                 # Scale factor for frames
  frame_dpi: 150             # DPI for frame generation
  quality: high              # Quality preset: low, medium, high

  # FFmpeg encoding parameters
  codec: h264_videotoolbox   # Video codec
  crf: 23                    # Constant Rate Factor
  preset: medium             # Encoding preset
  pix_fmt: yuv420p           # Pixel format
  
  # Additional FFmpeg options
  bitrate: null              # Target bitrate
  maxrate: null              # Maximum bitrate
  bufsize: null              # Buffer size
  
  # Quality settings
  tune: null                 # Tune for specific content
  profile: high              # H.264 profile
  level: 4.1                 # H.264 level
