# Configuration for 1D Rayleigh-Taylor Instability following Athena++ conventions
# Heavy fluid on top, light fluid on bottom, gravity pointing downward (in x direction)
# Dirichlet boundary conditions on both sides
problem: rti_1d

grid:
  N: 256                     # Resolution
  Lx: 2.0                    # Domain length (vertical direction)
  basis: legendre            # Legendre basis for non-periodic BCs
  bc: dirichlet              # Dirichlet BCs on both sides
  dealias: false             # Not applicable for Legendre basis
  precision: single          # Single precision for MPS compatibility

physics:
  gamma: 1.4                 # Adiabatic index

integration:
  t0: 0.0
  t_end: 2.0                 # Run for 2 time units to see instability growth
  cfl: 0.3                   # Conservative CFL for Legendre basis
  scheme: rk4                # Stable scheme for Legendre
  output_interval: 0.05      # Output every 0.05 time units
  checkpoint_interval: 0.2   # Checkpoints every 0.2 time units
  spectral_filter:
    enabled: true
    p: 8                     # Even integer >= 2
    alpha: 36.0              # Filter strength

# Adaptive time-stepping for efficiency
adaptive:
  enabled: true
  scheme: rk45
  rtol: 1e-5                 # Relaxed for single precision
  atol: 1e-7                 # Relaxed for single precision
  safety_factor: 0.9
  min_dt_factor: 0.1
  max_dt_factor: 5.0
  max_rejections: 10
  fallback_scheme: rk4

# Artificial viscosity for stability
artificial_viscosity:
  enabled: true
  mode: constant
  nu_constant: 0.0005        # Small constant viscosity
  variable_weights:
    density: 1.0
    momentum_x: 1.0
    energy: 1.0
  diagnostic_output: true

# Gravity configuration - pointing downward (negative x direction)
gravity:
  enabled: true
  type: "linear"
  gx: 1.0                    # Gravity pointing downward (in x direction for 1D)
  gy: 0.0
  gz: 0.0

# RTI initial conditions following Athena++ conventions
initial_conditions:
  rho_heavy: 2.0             # Heavy fluid density (top)
  rho_light: 1.0             # Light fluid density (bottom)
  pressure_top: 2.5          # Pressure at top boundary
  interface_thickness: 0.05  # Thickness of density transition layer
  perturb_amplitude: 0.01    # Amplitude of initial perturbation
  perturb_wavelength: 1.0    # Wavelength of perturbation (matches domain width)

io:
  outdir: outputs/rti_1d_athena
  save_spectra: true

monitoring:
  enabled: true
  step_interval: 50
  include_conservation: true
  include_timestep: true
  include_time: true
  include_velocity_stats: true
  include_density_stats: true

# Video generation settings
video:
  fps: 30
  width: 1280
  height: 720
  scale: 1.0
  frame_dpi: 120
  codec: h264_videotoolbox
  crf: 20
  preset: medium
  pix_fmt: yuv420p

runtime:
  num_threads: 4             # Use parallel Legendre operations
