# Configuration for 1D Shu-Osher problem with sophisticated stabilization
problem: shu_osher1d

grid:
  N: 4096
  Lx: 1.0
  dealias: true
  # basis: fourier        # default periodic basis
  # bc: null              # set when basis=chebyshev (e.g., dirichlet)

physics:
  gamma: 1.4

integration:
  t0: 0.0
  t_end: 0.02
  cfl: 0.01          # More conservative CFL
  scheme: rk45
  rtol: 1e-7         # Tighter tolerances
  atol: 1e-9
  output_interval: 0.01
  checkpoint_interval: 0.05
  spectral_filter:
    enabled: true
    p: 12             # Higher order filter
    alpha: 200.0       # Stronger filtering

# Minimal initial conditions smoothing - preserve physics!
initial_conditions_smoothing:
  enabled: true
  kernel_size: 0.001  # Minimal smoothing - just to avoid immediate instability
  mode: "wrap"
  variables: ["density"]  # Only smooth density, preserve velocity/pressure structure
  diagnostic_output: true

# Very tight adaptive time-stepping
adaptive:
  enabled: true
  scheme: rk45
  rtol: 1e-8          # Very tight tolerances
  atol: 1e-10
  safety_factor: 0.05 # Very conservative
  min_dt_factor: 0.01
  max_dt_factor: 2.0
  max_rejections: 20
  fallback_scheme: rk4

# Sophisticated artificial viscosity
artificial_viscosity:
  enabled: true
  nu_max: 5.0         # Higher maximum viscosity
  s_ref: 0.5          # Lower reference smoothness
  s_min: 0.01         # Much lower minimum smoothness
  p: 1.0              # Different power law
  epsilon: 1e-15      # Smaller epsilon for better detection
  variable_weights:
    density: 5.0      # Higher weight on density
    momentum_x: 3.0
    energy: 2.0
  sensor_variable: "density"
  diagnostic_output: true

# Enhanced monitoring
monitoring:
  enabled: true
  step_interval: 500  # More frequent monitoring
  include_conservation: true
  include_timestep: true
  include_time: true
  include_velocity_stats: true
  include_density_stats: true

io:
  outdir: outputs/shu_osher1d
  save_spectra: true

video:
  fps: 30
  width: 1920
  height: 1080
  scale: 2.0
  frame_dpi: 150
  codec: libopenh264
  crf: 18
  pix_fmt: yuv420p