# Configuration for 1D Sod shock tube problem
problem: sod

grid:
  N: 1024
  Lx: 1.0
  x0: 0.5               # discontinuity location
  dealias: true

physics:
  gamma: 1.4

integration:
  t0: 0.0
  t_end: 0.2
  cfl: 0.4
  scheme: rk45
  rtol: 1e-6
  atol: 1e-8
  output_interval: 0.01
  checkpoint_interval: 0.05
  spectral_filter:
    enabled: true
    p: 8
    alpha: 36.0

# Initial conditions smoothing (optional)
initial_conditions_smoothing:
  enabled: false        # Disabled by default for Sod problem
  kernel_size: 0.01     # 1% of domain length
  mode: "constant"      # Non-periodic boundary conditions
  variables: ["density", "velocity", "pressure"]
  diagnostic_output: false

# Adaptive time-stepping configuration
adaptive:
  enabled: true
  scheme: rk45          # rk23, rk45, rk78
  rtol: 1e-6            # Relative tolerance
  atol: 1e-8            # Absolute tolerance
  safety_factor: 0.9
  min_dt_factor: 0.1
  max_dt_factor: 5.0
  max_rejections: 10
  fallback_scheme: rk4

# Artificial viscosity configuration
artificial_viscosity:
  enabled: true
  nu_max: 1e-3          # Maximum viscosity coefficient
  s_ref: 1.0            # Reference smoothness threshold
  s_min: 0.1            # Minimum smoothness for applying viscosity
  p: 2.0                # Exponent for smoothness scaling
  epsilon: 1e-12        # Small number to avoid division by zero
  variable_weights:
    density: 1.0
    momentum_x: 1.0
    energy: 1.0
  sensor_variable: "density"
  diagnostic_output: true

# Initial conditions
initial_conditions:
  left:
    rho: 1.0
    u: 0.0
    p: 1.0
  right:
    rho: 0.125
    u: 0.0
    p: 0.1

io:
  outdir: outputs/sod
  save_spectra: true

monitoring:
  enabled: true
  step_interval: 100
  include_conservation: true
  include_timestep: true
  include_time: true
  include_velocity_stats: true
  include_density_stats: true

video:
  # Video generation parameters
  fps: 30                    # Frames per second
  width: 1920                # Output video width (0 = auto from frames)
  height: 1080               # Output video height (0 = auto from frames)
  scale: 2.0                 # Scale factor for frames (1.0 = original size)
  frame_dpi: 150             # DPI for frame generation (higher = better quality)

  # FFmpeg encoding parameters
  codec: h264_videotoolbox   # Video codec (h264_videotoolbox, libx264, libopenh264, etc.)
  crf: 18                    # Constant Rate Factor (0-51, lower = better quality)
  preset: medium             # Encoding preset (ultrafast, fast, medium, slow, veryslow)
  pix_fmt: yuv420p           # Pixel format (yuv420p, yuv444p, etc.)
  
  # Additional FFmpeg options
  bitrate: null              # Target bitrate (e.g., "2M" for 2 Mbps, null = use CRF)
  maxrate: null              # Maximum bitrate (e.g., "4M")
  bufsize: null              # Buffer size (e.g., "8M")
  
  # Quality settings
  tune: null                 # Tune for specific content (film, animation, grain, etc.)
  profile: high              # H.264 profile (baseline, main, high, high10, etc.)
  level: 4.1                 # H.264 level (3.0, 3.1, 4.0, 4.1, etc.)