# Configuration for 1D Sod shock tube problem with Legendre basis
problem: sod

grid:
  N: 256                    # Match Dedalus resolution
  Lx: 1.0
  x0: 0.5                   # discontinuity location
  basis: legendre           # Use Legendre basis for non-periodic BCs
  bc: dirichlet             # Reflecting walls: u=0 at both ends (Dirichlet)
  dealias: false          # Disable dealiasing for Legendre approach
  precision: double

physics:
  gamma: 1.4

integration:
  t0: 0.0
  t_end: 0.05               # Short test run
  cfl: 0.4
  scheme: rk45
  rtol: 1e-6
  atol: 1e-8
  output_interval: 0.01
  checkpoint_interval: 0.05
  spectral_filter:
    enabled: true
    p: 8
    alpha: 36.0

# Tanh-smoothed initial conditions (matching Dedalus script)
initial_conditions:
  left:
    rho: 1.0
    u: 0.0
    p: 1.0
  right:
    rho: 0.125
    u: 0.0
    p: 0.1
  smoothing:
    enabled: true
    sigma: 0.01              # Match Dedalus smoothing parameter

# Initial conditions smoothing (optional Gaussian smoothing)
initial_conditions_smoothing:
  enabled: false            # Disabled since we use tanh smoothing above

# Adaptive time-stepping configuration
adaptive:
  enabled: true
  scheme: rk45
  rtol: 1e-6
  atol: 1e-8
  safety_factor: 0.9
  min_dt_factor: 0.1
  max_dt_factor: 5.0
  max_rejections: 10
  fallback_scheme: rk4

# Constant artificial viscosity (matching Dedalus value)
artificial_viscosity:
  enabled: true             # Re-enable after fixing Legendre issue
  mode: constant
  nu_constant: 0.0003       # Match Dedalus nu = 3e-4
  variable_weights:
    density: 1.0
    momentum_x: 1.0
    energy: 1.0
  diagnostic_output: true

io:
  outdir: outputs/sod_legendre
  save_spectra: true

monitoring:
  enabled: true
  step_interval: 100
  include_conservation: true
  include_timestep: true
  include_time: true
  include_velocity_stats: true
  include_density_stats: true

video:
  fps: 30
  width: 1920
  height: 1080
  scale: 2.0
  frame_dpi: 150
  quality: high
  codec: h264_videotoolbox
  crf: 23
  preset: medium
  pix_fmt: yuv420p
  bitrate: null
  maxrate: null
  bufsize: null
  tune: null
  profile: high
  level: 4.1
