problem: tgv3d

grid:
  Nx: 128
  Ny: 128
  Nz: 64
  Lx: 6.283185307179586  # 2*pi
  Ly: 6.283185307179586  # 2*pi
  Lz: 6.283185307179586  # 2*pi
  dealias: true
  fft_workers: 4

physics:
  gamma: 1.4

integration:
  t0: 0.0
  t_end: 1.0
  cfl: 0.2
  scheme: rk4
  output_interval: 0.02
  spectral_filter:
    enabled: true
    p: 8
    alpha: 36.0


initial_conditions:
  rho0: 1.0
  p0: 100.0
  U0: 1.0
  k: 1

io:
  outdir: outputs/tgv3d
