# Configuration for 3D turbulent velocity field with adaptive time-stepping
problem: turb3d

grid:
  Nx: 64
  Ny: 64
  Nz: 64
  Lx: 1.0
  Ly: 1.0
  Lz: 1.0
  dealias: true
  fft_workers: 4 # only used on CPU backends

physics:
  gamma: 1.4

integration:
  t0: 0.0
  t_end: 2.0
  cfl: 0.8         # Upper bound for dt
  scheme: rk4       # Fallback for non-adaptive
  output_interval: 0.01
  spectral_filter:
    enabled: true
    p: 8
    alpha: 36.0
  
  # Adaptive time-stepping configuration
  adaptive:
    enabled: true
    scheme: rk45    # rk23, rk45, rk78
    rtol: 1e-4      # Relaxed for 3D complexity and turbulence
    atol: 1e-6      # Absolute tolerance
    safety_factor: 0.9
    min_dt_factor: 0.1
    max_dt_factor: 5.0
    max_rejections: 10
    fallback_scheme: rk4

initial_conditions:
  rho0: 1.0
  p0: 1.0
  vrms: 0.5  # Target RMS velocity magnitude
  kmin: 1.0  # Minimum wavenumber for band-pass
  kmax: 5.0  # Maximum wavenumber for band-pass (modes 1-5)
  alpha: 0.3333  # Compressive fraction (matching RAMSES comp_frac)
  spectrum_type: "power_law"  # Power law spectrum
  power_law_slope: -1.6666666666666667  # Kolmogorov slope (-5/3)
  seed: 4

io:
  outdir: outputs/turb3d_adaptive

video:
  # Video generation parameters
  fps: 30                    # Frames per second
  width: 1920                # Output video width (0 = auto from frames)
  height: 1080               # Output video height (0 = auto from frames)
  scale: 2.0                 # Scale factor for frames (1.0 = original size)
  frame_dpi: 150             # DPI for frame generation (higher = better quality)
  
  # 3D visualization parameters
  projection_type: "column_density"  # "slice" or "column_density"
  slice_axis: "z"            # Axis for slice (x, y, or z)
  slice_position: 0.5        # Position along slice axis (0-1)
  column_thickness: 1.0      # Thickness for column density integration (0-1)
  column_axis: "z"           # Axis for column density projection (x, y, or z)
  
  # Colorbar settings
  colorbar_scale: "log"      # "linear" or "log"
  colorbar_min: 0.5          # Minimum value for colorbar
  colorbar_max: 2.0          # Maximum value for colorbar
  colorbar_fixed: true       # Use fixed colorbar range (true) or auto (false)
  
  # FFmpeg encoding parameters
  codec: h264_videotoolbox   # Video codec (h264_videotoolbox, libx264, libopenh264, etc.)
  crf: 18                    # Constant Rate Factor (0-51, lower = better quality)
  preset: medium             # Encoding preset (ultrafast, fast, medium, slow, veryslow)
  pix_fmt: yuv420p           # Pixel format (yuv420p, yuv444p, etc.)
  
  # Additional FFmpeg options
  bitrate: null              # Target bitrate (e.g., "2M" for 2 Mbps, null = use CRF)
  maxrate: null              # Maximum bitrate (e.g., "4M")
  bufsize: null              # Buffer size (e.g., "8M")
  
  # Quality settings
  tune: null                 # Tune for specific content (film, animation, grain, etc.)
  profile: high              # H.264 profile (baseline, main, high, high10, etc.)
  level: 4.1                 # H.264 level (3.0, 3.1, 4.0, 4.1, etc.)

monitoring:
  enabled: true
  step_interval: 25
  include_conservation: true
  include_timestep: true
  include_time: true
  include_velocity_stats: true
  include_density_stats: true
